spring:
  application:
    name: cmbz-eureka
  config:
    import: optional:configserver:http://config-server:8080

eureka:
  instance:
    hostname: eureka
    prefer-ip-address: true
    instance-id: eureka

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8080/eureka/
