server:
  port: 8080

spring:
  application:
    name: cmbz-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: cmbz-user
          uri: lb://cmbz-user
          predicates:
            - Path=/api/v2/users/**
        - id: cmbz-user-auth
          uri: lb://cmbz-user
          predicates:
            - Path=/api/v2/authentication/**
        - id: cmbz-user-plans
          uri: lb://cmbz-user
          predicates:
            - Path=/api/v2/plans/**
        - id: cmbz-user-subscriptions
          uri: lb://cmbz-user
          predicates:
            - Path=/api/v2/subscriptions/**
        - id: cmbz-user-benefits
          uri: lb://cmbz-user
          predicates:
            - Path=/api/v2/benefits/**
        - id: cmbz-product
          uri: lb://cmbz-product
          predicates:
            - Path=/api/v2/products/**,/api/v2/product-categories/**,/api/v2/districts/**,/api/v2/favorite-products/**,/api/v2/countries/**,/api/v2/departments/**
        - id: cmbz-exchange
          uri: lb://cmbz-exchange
          predicates:
            - Path=/api/v2/exchanges/**,/api/v2/reviews/**
        - id: cmbz-donation
          uri: lb://cmbz-donation
          predicates:
            - Path=/api/v2/donations/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8080/eureka/
