server:
  port: 8090

spring:
  application:
    name: cmbz-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://backendcambiazo.mysql.database.azure.com:3306/userDb?sslMode=REQUIRED&allowPublicKeyRetrieval=true&useSSL=true
    username: cambiazo
    password: techZomovil2024
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.cambiazo.user.shared.infrastructure.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
