server:
  port: 8070

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: cmbz-exchange
  config:
    import: optional:configserver:https://cmbz-microservices-d5g5frgpafdbh9eb.westus-01.azurewebsites.net

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/exchangeDb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: cambiazo
    password: cambiazo123

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.cambiazo.exchange.shared.infrastructure.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

eureka:
  instance:
    hostname: cmbz-exchange.azurewebsites.net
    prefer-ip-address: false
    instance-id: cmbz-exchange.azurewebsites.net
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://cmbz-eureka.azurewebsites.net/eureka/
