version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cambiazo123
      MYSQL_USER: cambiazo
      MYSQL_PASSWORD: cambiazo123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - cambiazo

  config-server:
    container_name: config-server
    image: openjdk:21
    working_dir: /app
    volumes:
      - ./cambiazo-config/target:/app
      - ./cambiazo-config/src/main/resources/configurations:/app/configurations
    command: ["sh","-c","java -jar /app/*.jar"]
    ports:
      - "8888:8080"
    networks:
      - cambiazo

  eureka:
    container_name: eureka
    image: openjdk:21
    working_dir: /app
    volumes:
      - ./cambiazo-eureka/target:/app
    command: ["sh","-c","java -jar /app/*.jar"]
    ports:
      - "8761:8080"
    depends_on:
      - config-server
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
    networks:
      - cambiazo

  gateway:
    container_name: gateway
    image: openjdk:21
    working_dir: /app
    volumes:
      - ./cambiazo-gateway/target:/app
    command: ["sh","-c","java -jar /app/*.jar"]
    ports:
      - "8080:8080"
    depends_on:
      - eureka
      - config-server
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
    networks:
      - cambiazo

  cmbz-user:
    container_name: cmbz-user
    image: openjdk:21
    working_dir: /app
    volumes:
      - ./cambiazo-user/target:/app
    command: ["sh","-c","java -jar /app/*.jar"]
    ports:
      - "8081:8080"
    depends_on:
      - eureka
      - config-server
      - mysql
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
    networks:
      - cambiazo

  cmbz-product:
    container_name: cmbz-product
    image: openjdk:21
    working_dir: /app
    volumes:
      - ./cambiazo-product/target:/app
    command: ["sh","-c","java -jar /app/*.jar"]
    ports:
      - "8082:8080"
    depends_on:
      - eureka
      - config-server
      - mysql
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
    networks:
      - cambiazo

  cmbz-exchange:
    container_name: cmbz-exchange
    image: openjdk:21
    working_dir: /app
    volumes:
      - ./cambiazo-exchange/target:/app
    command: ["sh","-c","java -jar /app/*.jar"]
    ports:
      - "8083:8080"
    depends_on:
      - eureka
      - config-server
      - mysql
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
    networks:
      - cambiazo

  cmbz-donation:
    container_name: cmbz-donation
    image: openjdk:21
    working_dir: /app
    volumes:
      - ./cambiazo-donation/target:/app
    command: ["sh","-c","java -jar /app/*.jar"]
    ports:
      - "8084:8080"
    depends_on:
      - eureka
      - config-server
      - mysql
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
    networks:
      - cambiazo

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gateway
    networks:
      - cambiazo

volumes:
  mysql_data:

networks:
  cambiazo:
    driver: bridge