events {}

http {
  upstream config-server {
    server config-server:8080;
  }

  upstream eureka {
    server eureka:8080;
  }

  upstream cmbz-user {
    server cmbz-user:8080;
  }

  upstream cmbz-product {
    server cmbz-product:8080;
  }

  upstream cmbz-exchange {
    server cmbz-exchange:8080;
  }

  upstream cmbz-donation {
    server cmbz-donation:8080;
  }

  upstream gateway {
    server gateway:8080;
  }

  server {
    listen 80;

    location /config/ {
      proxy_pass http://config-server/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /eureka/ {
      proxy_pass http://eureka/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/v2/users/ {
      proxy_pass http://cmbz-user/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/v2/products/ {
      proxy_pass http://cmbz-product/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/v2/exchange/ {
      proxy_pass http://cmbz-exchange/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/v2/donations/ {
      proxy_pass http://cmbz-donation/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
      proxy_pass http://gateway/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
