events {}

http {
  upstream eureka {
    server eureka:8761;
  }

  upstream config {
    server config:8888;
  }

  upstream user {
    server user:8081;
  }

  upstream product {
    server product:8082;
  }

  upstream exchange {
    server exchange:8083;
  }

  upstream donation {
    server donation:8084;
  }

  upstream gateway {
    server gateway:8080;
  }

  server {
    listen 80;

    location /eureka/ {
      proxy_pass http://eureka/;
    }

    location /config/ {
      proxy_pass http://config/;
    }

    location /api/v2/users/ {
      proxy_pass http://user/;
    }

    location /api/v2/products/ {
      proxy_pass http://product/;
    }

    location /api/v2/exchange/ {
      proxy_pass http://exchange/;
    }

    location /api/v2/donations/ {
      proxy_pass http://donation/;
    }

    location / {
      proxy_pass http://gateway/;
    }
  }
}
