spring:
  application:
    name: cmbz-exchange
  config:
    import: optional:configserver:http://localhost:8888
jwt:
  secret: "f504d11617821d4d6e371dcffd085af94941a9b8219539e7ea9462b7dcb92248"
  expiration-ms: 3600000
